spring.application.name=taskmanagement
spring.thymeleaf.cache=false
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/index.html
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
